server:
  address: 127.0.0.1
  port: 8083

spring:
  application:
    name: servicio-documentos
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xepdb1
    username: ${DB_USERNAME:user_hc}
    password: ${DB_PASSWORD:secure_password_2025}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect

security:
  jwt:
    secret: ${JWT_SECRET:cambia-esta-clave-super-segura-de-32+caracteres-2025}
